name: Build RMK Firmware

on:
  workflow_dispatch:
  push:
    paths:
      - "**"

jobs:
  # 利用矩阵策略，分别传入 3 个不同的编译目标给官方的工作流
  build:
    strategy:
      matrix:
        target: [central, peripheral_left, peripheral_right]
    
    # 完美调用官方推荐的可复用工作流
    uses: haobogu/rmk/.github/workflows/user_build.yml@main
    with:
      keyboard_toml_path: "keyboard.toml"
      vial_json_path: "vial.json"
      # 将矩阵中的 target 变量直接喂给官方工作流
      # （注：官方 user_build.yml 通常提供了 target 参数。如果该参数名有出入，它也会默认读取你 toml 内的特征）
      target: ${{ matrix.target }}
